<a href="https://colab.research.google.com/github/OnzyBoy/Python_CDAV/blob/main/8_CDAV_python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Numerical Python

*   Perform Numerical Operations on a subset oof data
*   List item



In [1]:
import numpy as np #Aliasing w/ 'as' keyword

print(np.__version__)

2.0.2


In [26]:
#Nd Arrays
# To know dimensions, chack the opening and closing brackets
arr = np.array(20) # 0 dimensions basically a list

arr = np.array([1,2,3,4,5]) # 1 dimension

arr = np.array([[1,2,3],[4,5,6]]) # 2 dimensions

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 dimensions
arr = np.array([[[1,2,3], [40,50,60]]]) # 3 dimensions

arr = np.array([[[[20,30, 40], [10,15,54], [60,70,80]]]]) #4 dimensions
print(arr.shape) #  returns a tuple with each index having the number of corresponding elements
print(f"Dimensions: {arr.ndim}") # Gives Dimension of an array

Dimensions: 2
(1, 1, 3, 3)


In [75]:
# 1D Array w/ 4 items
ar = np.array([1,2,3,4])

# 2D Array w/ 3 items in the 1st dimension and 4 items in the second one
ar = np.array([[1,2,3,4],[1,2,3,4],[10,20,30,40]])

# 3D array w/ 2 items in the first, 2 in the second and 2 in the 3rd one
ar = np.array([[[2,4],[10,12],[15,17]]])

# 5d Array w/ 2 items in the first, 1 item in the second, 2 items in the third, 1 item in the 4th and 3 items in the 5th (2,1,2,1,3)
ar = np.array([[[[[1,2,3]],[[4,5,6]]]],[[[[7,8,9]],[[10,11,12]]]]])


print(f"Shape: {ar.shape}")
print(f"Dimensions: {ar.ndim}")


Shape: (2, 1, 2, 1, 3)
Dimensions: 5


In [76]:
#Range of an arrays
np.arange(0,10,2) # (start, stop, step)

array([0, 2, 4, 6, 8])

In [78]:
np.zeros([2,2]) # (shape)

array([[0., 0.],
       [0., 0.]])

In [81]:
#To change the shape of an array
arr_1 = np.array([2,1])
arr_1.ndim

arr_1 = arr_1.reshape(1,2)
arr_1.ndim

#Converting mulitple dimensions to become 1 dimension - 'Array Flattening'
arr_1 = arr_1.reshape(-1)
arr_1.ndim

1

In [91]:
#Create a 10D array with values between 1 and 10000
arr = np.arange(1,10001)
arr_10 = arr.reshape(10,10,10,10,1,1,1,1,1,1)
arr_10.ndim


10

In [93]:
arr = np.random.rand(2,2)
print(arr)

[[0.89558085 0.98372604]
 [0.58872972 0.40056856]]
