<a href="https://colab.research.google.com/github/OnzyBoy/Python_CDAV/blob/main/8_CDAV_python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Numerical Python

*   Perform Numerical Operations on a subset oof data
*   List item



In [ ]:
import numpy as np #Aliasing w/ 'as' keyword

print(np.__version__)

2.0.2


In [ ]:
#Nd Arrays
# To know dimensions, chack the opening and closing brackets
arr = np.array(20) # 0 dimensions basically a list

arr = np.array([1,2,3,4,5]) # 1 dimension

arr = np.array([[1,2,3],[4,5,6]]) # 2 dimensions

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 dimensions
arr = np.array([[[1,2,3], [40,50,60]]]) # 3 dimensions

arr = np.array([[[[20,30, 40], [10,15,54], [60,70,80]]]]) #4 dimensions
print(arr.shape) #  returns a tuple with each index having the number of corresponding elements
print(f"Dimensions: {arr.ndim}") # Gives Dimension of an array

Dimensions: 2
(1, 1, 3, 3)


In [ ]:
# 1D Array w/ 4 items
ar = np.array([1,2,3,4])

# 2D Array w/ 3 items in the 1st dimension and 4 items in the second one
ar = np.array([[1,2,3,4],[1,2,3,4],[10,20,30,40]])

# 3D array w/ 2 items in the first, 2 in the second and 2 in the 3rd one
ar = np.array([[[2,4],[10,12],[15,17]]])

# 5d Array w/ 2 items in the first, 1 item in the second, 2 items in the third, 1 item in the 4th and 3 items in the 5th (2,1,2,1,3)
ar = np.array([[[[[1,2,3]],[[4,5,6]]]],[[[[7,8,9]],[[10,11,12]]]]])


print(f"Shape: {ar.shape}")
print(f"Dimensions: {ar.ndim}")


Shape: (2, 1, 2, 1, 3)
Dimensions: 5


In [ ]:
#Range of an arrays
np.arange(0,10,2) # (start, stop, step)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros([2,2]) # (shape)

array([[0., 0.],
       [0., 0.]])

In [ ]:
#To change the shape of an array
arr_1 = np.array([2,1])
arr_1.ndim

arr_1 = arr_1.reshape(1,2)
arr_1.ndim

#Converting mulitple dimensions to become 1 dimension - 'Array Flattening'
arr_1 = arr_1.reshape(-1)
arr_1.ndim

1

In [ ]:
#Create a 10D array with values between 1 and 10000
arr = np.arange(1,10001)
arr_10 = arr.reshape(10,10,10,10,1,1,1,1,1,1)
arr_10.ndim


10

In [ ]:
arr = np.random.rand(2,2)
print(arr)

[[0.89558085 0.98372604]
 [0.58872972 0.40056856]]


In [ ]:
# Write a function describe_array(arr) that: | # Prints the type of array (1D, 2D, 3D) | # Prints its shape, and dtype | # Flattens the array and returns it
import numpy as np

def describe_array(arr):
    # Print array type
    print(f"This is a {arr.ndim}D array.")

    # Print shape and dtype
    print("Shape:", arr.shape)
    print("Data type:", arr.dtype)

    # Flatten - To 1D
    flat = arr.flatten()
    return flat

arr = np.array([[[2,3,4],[5,6,8]]])
flat_array = describe_array(arr)
print("Flattened array:", flat_array)
print(arr.size)

This is a 3D array.
Shape: (1, 2, 3)
Data type: int64
Flattened array: [2 3 4 5 6 8]
6


# Accessing Arrays

In [ ]:
#Accesing 1d arrays, like a list
arr_1 = np.array([1,2,4,4,5,7])
arr_1[5]

#Accessing 2D arrays
arr_2 = np.array([[1,2],[3,4]])
arr_2[0,0] #1
arr_2[1,0] #3

#Accessing 3d Arrays
arr_3 = np.array([[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]] )
arr_3[1,0,1]#6
arr_3.shape

(3, 2, 2)

In [ ]:
#Accessing Mulitiple Values via slicing
#1d Arrays
arr_1 = np.array([1,2,4,4,5,7])
arr_1[0:2] # 1 and 2

#2d arrays
arr_2 = np.array([[1,2],[3,4]])
arr_2[0,0:2] # 1 and 2
arr_2[0:,0] # 1 and 3

# 3d arrays
arr_3 = np.array([[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]] )

array([1, 3])

In [ ]:
arr_4 = np.array([[1,2],[3,4], [5,6], [7,8]])
arr_4[0:2] #first 2 lists
arr_4[0:2,0] #1 and 3
arr_4[3,1] #8
arr_4[2:,0] #5 and 7

array([5, 7])

In [ ]:
# Use the array below to extract the values shown:
# [40,20,40,10] | [20,70,10] | [10,30,10] | [70,70]

arr_5 = np.array([[[40,20,50],[20,40,60],[40,30,20]],[[10,40,70],[10,30,10],[20,50,70]]])
arr_5.shape

arr_1 = arr_5[0:1,0:3,0]#40 20 40
arr_2 = arr_5[1,0,0] # 10
new_arr = arr_1, arr_2

arr_3 = arr_5[0,1,0] # 20
arr_4 = arr_5[1,0:2,2] # 70,10
new_arr = arr_3,arr_4
# print(new_arr)


arr_5[0:,0:,0].flatten()[:4] #40,20,40
arr_5[0:,0:,2].flatten()[2:5] #20,70,10
arr_5[1,1] # 10,30,10
arr_5[1,0::2,2] #70,70

array([10, 40, 70, 10, 30, 10])

array([40, 20, 40, 10])

# Index Positioning

.where() gets the index position of a given value in an array

In [ ]:
arr_4 = np.array([[1,2],[3,4],[5,6],[7,8]])
np.where(arr_4==6)
arr_4[2,1] #6

arr_5 = np.array([[[40,20,50],[20,40,60],[40,30,20]],[[10,40,70],[10,30,10],[20,50,70]]])
np.where(arr_5 == 40)
arr_5[1,0,1] #40

(array([0, 0, 0, 1]), array([0, 1, 2, 0]), array([0, 1, 0, 1]))

# Filtering

In [ ]:
arr_4 = np.arange(0,20) #0-19
arr_even = arr_4[arr_4%2==0] #Even numbers

arr_even[arr_even>15]


array([16, 18])

In [ ]:
#Casting from integer to string
arr_4.astype("str_")

arr_7 = np.array(["soap", 40, "milk", 50])
arr_7.dtype

dtype('<U21')

# Operations

In [ ]:
arr_1 = np.array([2,2])
arr_3 = np.array([3,4])

print(arr_1 + arr_3) # [5,6]
print(arr_1 - arr_3) # [-1,-2]
print(arr_1 * arr_3) # [6,8]
print(arr_1 / arr_3)

print(f"Sum: {sum(arr_1)}") # 4
print(f"Minimum: {min(arr_3)} ") # 3


[5 6]
[-1 -2]
[6 8]
[0.66666667 0.5       ]
Sum: 4
Minimum 3 


In [ ]:
#Joining arrays with np.concatenate
np.concatenate((arr_1,arr_3))

arr_c = np.array([[1,2], [3,4]])
arr_d = np.array([[5,6], [7,8]])
np.concatenate((arr_c,arr_d), axis=1) #axis 0 - columns(default); axis1 - rows

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#Copying - don't affect original
arr_6 = np.arange(0,20)
arr_6_copy = arr_6.copy()
arr_6[0] = 100
arr_6_copy
arr_6

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [ ]:
#Replication - affect original array
arr_6_view = arr_6.view()
arr_6[0] = 500
arr_6_view

print(arr_6_copy.base) #None - not dependent on an array
print(arr_6_view.base) #arr_6 - dependent on an array

None
[500   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
