<a href="https://colab.research.google.com/github/OnzyBoy/Python_CDAV/blob/main/8_CDAV_python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Numerical Python

*   Perform Numerical Operations on a subset oof data
*   List item



In [ ]:
import numpy as np #Aliasing w/ 'as' keyword

print(np.__version__)

2.0.2


In [ ]:
#Nd Arrays
# To know dimensions, chack the opening and closing brackets
arr = np.array(20) # 0 dimensions basically a list

arr = np.array([1,2,3,4,5]) # 1 dimension

arr = np.array([[1,2,3],[4,5,6]]) # 2 dimensions

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 dimensions
arr = np.array([[[1,2,3], [40,50,60]]]) # 3 dimensions

arr = np.array([[[[20,30, 40], [10,15,54], [60,70,80]]]]) #4 dimensions
print(arr.shape) #  returns a tuple with each index having the number of corresponding elements
print(f"Dimensions: {arr.ndim}") # Gives Dimension of an array

Dimensions: 2
(1, 1, 3, 3)


In [ ]:
# 1D Array w/ 4 items
ar = np.array([1,2,3,4])

# 2D Array w/ 3 items in the 1st dimension and 4 items in the second one
ar = np.array([[1,2,3,4],[1,2,3,4],[10,20,30,40]])

# 3D array w/ 2 items in the first, 2 in the second and 2 in the 3rd one
ar = np.array([[[2,4],[10,12],[15,17]]])

# 5d Array w/ 2 items in the first, 1 item in the second, 2 items in the third, 1 item in the 4th and 3 items in the 5th (2,1,2,1,3)
ar = np.array([[[[[1,2,3]],[[4,5,6]]]],[[[[7,8,9]],[[10,11,12]]]]])


print(f"Shape: {ar.shape}")
print(f"Dimensions: {ar.ndim}")


Shape: (2, 1, 2, 1, 3)
Dimensions: 5


In [ ]:
#Range of an arrays
np.arange(0,10,2) # (start, stop, step)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros([2,2]) # (shape)

array([[0., 0.],
       [0., 0.]])

In [ ]:
#To change the shape of an array
arr_1 = np.array([2,1])
arr_1.ndim

arr_1 = arr_1.reshape(1,2)
arr_1.ndim

#Converting mulitple dimensions to become 1 dimension - 'Array Flattening'
arr_1 = arr_1.reshape(-1)
arr_1.ndim

1

In [ ]:
#Create a 10D array with values between 1 and 10000
arr = np.arange(1,10001)
arr_10 = arr.reshape(10,10,10,10,1,1,1,1,1,1)
arr_10.ndim


10

In [ ]:
arr = np.random.rand(2,2)
print(arr)

[[0.89558085 0.98372604]
 [0.58872972 0.40056856]]


In [ ]:
# Write a function describe_array(arr) that: | # Prints the type of array (1D, 2D, 3D) | # Prints its shape, and dtype | # Flattens the array and returns it
import numpy as np

def describe_array(arr):
    # Print array type
    print(f"This is a {arr.ndim}D array.")

    # Print shape and dtype
    print("Shape:", arr.shape)
    print("Data type:", arr.dtype)

    # Flatten - To 1D
    flat = arr.flatten()
    return flat

arr = np.array([[[2,3,4],[5,6,8]]])
flat_array = describe_array(arr)
print("Flattened array:", flat_array)
print(arr.size)

This is a 3D array.
Shape: (1, 2, 3)
Data type: int64
Flattened array: [2 3 4 5 6 8]
6


# Accessing Arrays

In [ ]:
#Accesing 1d arrays, like a list
arr_1 = np.array([1,2,4,4,5,7])
arr_1[5]

#Accessing 2D arrays
arr_2 = np.array([[1,2],[3,4]])
arr_2[0,0] #1
arr_2[1,0] #3

#Accessing 3d Arrays
arr_3 = np.array([[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]] )
arr_3[1,0,1]#6
arr_3.shape

(3, 2, 2)

In [ ]:
#Accessing Mulitiple Values via slicing
#1d Arrays
arr_1 = np.array([1,2,4,4,5,7])
arr_1[0:2] # 1 and 2

#2d arrays
arr_2 = np.array([[1,2],[3,4]])
arr_2[0,0:2] # 1 and 2
arr_2[0:,0] # 1 and 3

# 3d arrays
arr_3 = np.array([[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]] )

array([1, 3])

In [ ]:
arr_4 = np.array([[1,2],[3,4], [5,6], [7,8]])
arr_4[0:2] #first 2 lists
arr_4[0:2,0] #1 and 3
arr_4[3,1] #8
arr_4[2:,0] #5 and 7

array([5, 7])

In [ ]:
# Use the array below to extract the values shown:
# [40,20,40,10] | [20,70,10] | [10,30,10] | [70,70]

arr_5 = np.array([[[40,20,50],[20,40,60],[40,30,20]],[[10,40,70],[10,30,10],[20,50,70]]])
arr_5.shape

arr_1 = arr_5[0:1,0:3,0]#40 20 40
arr_2 = arr_5[1,0,0] # 10
new_arr = arr_1, arr_2

arr_3 = arr_5[0,1,0] # 20
arr_4 = arr_5[1,0:2,2] # 70,10
new_arr = arr_3,arr_4
# print(new_arr)


arr_5[0:,0:,0].flatten()[:4] #40,20,40
arr_5[0:,0:,2].flatten()[2:5] #20,70,10
arr_5[1,1] # 10,30,10
arr_5[1,0::2,2] #70,70

array([10, 40, 70, 10, 30, 10])

array([40, 20, 40, 10])

# Index Positioning

.where() gets the index position of a given value in an array

In [ ]:
arr_4 = np.array([[1,2],[3,4],[5,6],[7,8]])
np.where(arr_4==6)
arr_4[2,1] #6

arr_5 = np.array([[[40,20,50],[20,40,60],[40,30,20]],[[10,40,70],[10,30,10],[20,50,70]]])
np.where(arr_5 == 40)
arr_5[1,0,1] #40

(array([0, 0, 0, 1]), array([0, 1, 2, 0]), array([0, 1, 0, 1]))

# Filtering

In [ ]:
arr_4 = np.arange(0,20) #0-19
arr_even = arr_4[arr_4%2==0] #Even numbers

arr_even[arr_even>15]


array([16, 18])

In [ ]:
#Casting from integer to string
arr_4.astype("str_")

arr_7 = np.array(["soap", 40, "milk", 50])
arr_7.dtype

dtype('<U21')

# Operations

In [ ]:
arr_1 = np.array([2,2])
arr_3 = np.array([3,4])

print(arr_1 + arr_3) # [5,6]
print(arr_1 - arr_3) # [-1,-2]
print(arr_1 * arr_3) # [6,8]
print(arr_1 / arr_3)

print(f"Sum: {sum(arr_1)}") # 4
print(f"Minimum: {min(arr_3)} ") # 3


[5 6]
[-1 -2]
[6 8]
[0.66666667 0.5       ]
Sum: 4
Minimum 3 


In [ ]:
#Joining arrays with np.concatenate
np.concatenate((arr_1,arr_3))

arr_c = np.array([[1,2], [3,4]])
arr_d = np.array([[5,6], [7,8]])
np.concatenate((arr_c,arr_d), axis=1) #axis 0 - columns(default); axis1 - rows

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#Copying - don't affect original
arr_6 = np.arange(0,20)
arr_6_copy = arr_6.copy()
arr_6[0] = 100
arr_6_copy
arr_6

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [ ]:
#Replication - affect original array
arr_6_view = arr_6.view()
arr_6[0] = 500
arr_6_view

print(arr_6_copy.base) #None - not dependent on an array
print(arr_6_view.base) #arr_6 - dependent on an array

None
[500   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [ ]:
# Task: Arrays in numpy

# Print the total score for each test. | # Print the highest and lowest scores in each test.|# Print the average score in each test.
# Print the score of student 5 in both tests.| # Compute the total score for each student (row-wise sum).

test1_scores = np.array([45, 78, 62, 89, 90, 56, 77, 83])
test2_scores = np.array([52, 74, 69, 88, 95, 61, 79, 85])

# Print the total score for each test.
print(f"Total Test One Scores: {sum(test1_scores)}")
print(f"Total Test Two Scores: {sum(test2_scores)} \n")

# Print the highest and lowest scores in each test.
#Test 1
print(f"Test One Highest Score: {max(test1_scores)}")
print(f"Test One Lowest Score: {min(test1_scores)}")
#Test 2
print(f"Test Two Highest Score: {max(test2_scores)}")
print(f"Test Two Lowest Score: {min(test2_scores)}\n")

# Print the average score in each test.
print(f"Test One Average Score: {np.average(test1_scores)}")
print(f"Test Two Average Score: {np.average(test2_scores)}\n")

# Print the score of student 5 in both tests.
print(f"Student Five Test One Score: {test1_scores[4]}")
print(f"Student Five Test Two Score: {test2_scores[4]}\n")

# Compute the total score for each student (row-wise sum).
student_scores = test1_scores + test2_scores
print(f"Student Scores: {student_scores}")

Total Test One Scores: 580
Total Test Two Scores: 603 

Test One Highest Score: 90
Test One Lowest Score: 45
Test Two Highest Score: 95
Test Two Lowest Score: 52

Test One Average Score: 72.5
Test Two Average Score: 75.375

Student Five Test One Score: 90
Student Five Test Two Score: 95

Student Scores: [ 97 152 131 177 185 117 156 168]


# Vectorization

Perfoming operations in arrays w/out looping

Components
*   Function to perform operations
*   numpy function to convert function to a vector function
*   Call your function on your array
*   Vectorized functions are calles ufunc

In [ ]:
# A 2d Array containing even numbers between 1-20 (inclusive) shape (2,5)| Get squares
#Shorter Way
arr_2d = np.arange(2,21,2).reshape(2,5)

# arr = np.array([])
# #Even Numbers
# for i in range(2,21,2):
#   arr = np.append(arr,i)
# arr_2d = arr.reshape(2,5)

# #Even Numbers option 2
# for i in range(1,21):
#   if i%2==0:
#     arr = np.append(arr,i)
# arr_2d = arr.reshape(2,5)

print(arr_2d)
print("Powers")
for x in arr_2d:
  for y in x:
    print(np.power(y,2))

print("\nVector Function Powers")
#Vector Function
np.power(arr_2d,2)



[[ 2  4  6  8 10]
 [12 14 16 18 20]]
Powers
4
16
36
64
100
144
196
256
324
400

Vector Function Powers


array([[  4,  16,  36,  64, 100],
       [144, 196, 256, 324, 400]])

In [ ]:
#Vectorize a function - np.frompyfunc(function_name, no_of_inputs, number_of_outputs)
#or np.vectorize(function_name)

#1. Define a function
def make_lower(name):
  return name.lower()

#2. Vectorize the function
#Method 1
# to_lower = np.vectorize(make_lower)
#Method 2
to_lower = np.frompyfunc(make_lower,1,1)

#3.Call your function on your array
str_array = np.array(["James","John","Jude","Jane"])

print(to_lower(str_array))

['james' 'john' 'jude' 'jane']


In [59]:
def getYearOfBirth(ages):
  return 2025 - ages

age_vec = np.vectorize(getYearOfBirth)

ages = np.array([34,25,50,56,23,12,78,50,12])

#print(age_vec(ages))

# print an array of strings as follows:
# ['Peter spent 50' 'Mary spent 90' 'Edward spent 28' 'John spent 80']
def sales (name, qty, price):
  total = int(qty) * price
  # return f"{name} spent {total}"
  return name + " spent " + str(total)

sales_vec = np.vectorize(sales)

customer_array = np.array(["Peter","Mary","Edward","John"])
quantities = np.array(["1", "3", "4", "1"])
item_prices = np.array([50, 30, 7, 80])
print(sales_vec(customer_array, quantities,item_prices))

['Peter spent 50' 'Mary spent 90' 'Edward spent 28' 'John spent 80']
